### ISSUE TITLE
Migration fails for the design docs without views

### ISSUE THREAD

**Issue by papahmsolo** [glynnbird/couchmigrate#6]
**Problem**
_Couchmigrate_ fails with error when trying to migrate the design document that does not have `view` in it.

**How to reproduce**
This design document has only `update` function
```{
  "_id": "_design/my_doc",
  "language": "javascript",
  "updates": {
    "update_config": "function (doc, req) {\r\n  try {\r\n    if (!req.id) { throw \"ID is not specified\" }\r\n    if (!req.query.lastFetchingDate) { throw \"lastFetchingDate is not specified\"; }\r\n\r\n    var currentTimeStamp = new Date().toISOString();\r\n    var lastFetchingDate = req.query.lastFetchingDate;\r\n\r\n    doc.lastFetchingDate = lastFetchingDate;\r\n    doc.updated = currentTimeStamp;\r\n\r\n    return [doc, {\r\n      \"code\": 200,\r\n      \"headers\": {\r\n        \"Content-Type\": \"application/json\"\r\n      },\r\n      \"body\": JSON.stringify({\r\n        returnCode: 200,\r\n        returnMessage: \"Successfully updated\"\r\n      })\r\n    }];\r\n  } catch (e) {\r\n    return [null, {\r\n      \"code\": 400,\r\n      \"headers\": {\r\n        \"Content-Type\": \"application/json\"\r\n      },\r\n      \"body\": JSON.stringify({\r\n        returnCode: 400,\r\n        returnMessage: e\r\n      })\r\n    }];\r\n  }\r\n}"
  }
}
```

when you run _couchmigrate_ against it you'll get the following error:

```..\npm\node_modules\couchmigrate\app.js:209
            var v = Object.keys(dd.views)[0];
                           ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ..\npm\node_modules\couchmigrate\app.js:209:28
    at Object.doWhilst (..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:3010:5)
    at ..\npm\node_modules\couchmigrate\app.js:205:13
    at ..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:3866:24
    at replenish (..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:998:17)
    at iterateeCallback (..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:983:17)
    at ..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:958:16
    at ..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:3871:13
    at ..\npm\node_modules\couchmigrate\node_modules\async\dist\async.js:3874:9
```
**Assumption**
Looks like _couchmigrate_ is trying to trigger a `view` build, which it should not do as there's no `view` in this design document.

**Comment by glynnbird** [comment]
Thanks. Definitely a bug. I'll fix :)
